### ISSUE TITLE
Source input problem

### ISSUE THREAD

**Issue by moodygit** [giraffi/fluent-plugin-amqp#12]
This is my td-agent conf:

```
<source>
  type amqp
  host rabbitmq.hostname - local rabbitmq(same instance with td-agent)
  port 5672
  vhost /
  user test
  pass test
  queue logs
  format json
</source>

<match **>
  type file
  path /var/log/logs/test
  time_slice_format %Y%m%d%H
  time_slice_wait 1s
  utc
  buffer_chunk_limit 1m
</match>
```

For testing RMQ I use https://github.com/backstop/rabbit-mq-stress-tester
I see in RMQ dashboard request, but nothing in /var/log/logs/test and nothing in logs files

Thank you

**Comment by sawanoboly** [comment]
When you start the td-agent, the queue named `logs` had been available?
If queue is exists, you can send message manually from RabbitMQ management console. Could you check these?

**Comment by moodygit** [comment]
**mq-stress-tester** made _stress-test-exchange_ queue whit Messages. I also see _logs_ queue, but it is empty. http://s8.postimg.org/pxys6wrdh/Untitled.png

**Comment by sawanoboly** [comment]
Please try to subscribe `stress-test-exchange` by td-agent. like below.

```
<source>
  type amqp
  host rabbitmq.hostname - local rabbitmq(same instance with td-agent)
  port 5672
  vhost /
  user test
  pass test
  queue stress-test-exchange
  format json
</source>

...
```

**Comment by moodygit** [comment]
Yes, I changed queue name to _stress-test-exchange_  just as wrote previous message. I found the problem. **durable**! durable=true, now I see messages in _ /var/log/logs/test_ Thank you

**Comment by moodygit** [comment]
also was tested on remote td-agent. all works. thanks

**Comment by sawanoboly** [comment]
:+1:

**Comment by ebuildy** [comment]
Woa, durable => true, makes it work too, why?

**Comment by sawanoboly** [comment]
@ebuildy If I remember correctly, both of producer and consumer shuold use same durable paramater. This behavior depends on producer's setting.
