### ISSUE TITLE
Query: How is this plugin actually released?

### ISSUE THREAD

**Issue by warmfusion** [giraffi/fluent-plugin-amqp#31]
So I've been wondering - How does this plugin get released into Rubygems?

Do you just build and publish from local workstation - What commands are used?

**Comment by sawanoboly** [comment]
It need 2 commands.

- `git pull`
- `rake release`


If you'd like to release this gem to rubygems, I'll grant two rights to you.

- Allow write permission to this repo.
- Add you as Collaborators of https://rubygems.org/gems/fluent-plugin-amqp

**Comment by warmfusion** [comment]
I'm happy to do that; its upto you guys if you're alright with me being able to release those changes?

**Comment by sawanoboly** [comment]
Yes, of course 👍  Do you have account of rubygems.org ?

**Comment by warmfusion** [comment]
This is me: https://rubygems.org/profiles/warmfusion

**Comment by warmfusion** [comment]
I'll still use pull requests for anything that modifies the Major or Minor versions, or anything that I'd like some feedback on, but I'll probably start releasing patches as i come across problems and resolve them safely if thats ok?

**Comment by sawanoboly** [comment]
Yes, you can release when you need. I've granted rights to you for release this gem. Could you confirm at next release?

**Comment by warmfusion** [comment]
The UX suggests i can release; I'll go hunting for things to fix and patch up accordingly.

Thanks for the invitation. 👍
