### ISSUE TITLE
Allow source to specify message 'content-type'

### ISSUE THREAD

**Issue by Phrozyn** [giraffi/fluent-plugin-amqp#37]
Right now my json messages are being input as application/octet-stream
is there a way to specify application/json?

**Comment by warmfusion** [comment]
I'm not sure I understand; input into what? Are you meaning the source or matcher part of this plugin?

Can you give some example of your configuration and the messages being handled?

**Comment by Phrozyn** [comment]
So I have heka pointing events to rabbitmq and need to replace it, we'd like to use fluentd with a rabbitmq plugin. 
Here is an example of how the output is seen

Expected output:
eventtask........'.<...........@.application/json....X.N-........{"json code here"}

Actual output:
eventtask........-.<.............application/octet-stream..............{"json code here"}


If you look at this other unmaintained amqp plugin, he had an option for content type, and I didn't see one in this amqp plugin so I thought I'd ask

**Comment by Phrozyn** [comment]
nevermind! They just showed up!

The server reported 1905 messages remaining.
Exchange 	(AMQP default)
Routing Key 	eventtask
Redelivered 	●
Properties 	
priority:	0
delivery_mode:	1
headers:	
content_type:	application/octet-stream
Payload
236 bytes
Encoding: string
	

{"timestamp":"2017-03-01T23:37:33+00:00","hostname":"new-random.hostname.com","program":"kernel","processid":null,"type":"syslog","logger":"systemslogs","payload":"[164664.907984] audit_printk_skb: 12 callbacks suppressed"}

**Comment by Phrozyn** [comment]
So when consuming these messages my app expects application/json
It sees application/octet-stream

resulting in:

KeyError: 'octet-stream'

I can likely code for this, but it would be nice to be able to set the content-type appropriately.

**Comment by Phrozyn** [comment]
I also tried to specify format json, but I get the following:
My config:

  <match syslog>
    @type amqp
    host "random.host.com"
    port 5672
    format json
    user "mozdef"
    pass xxxxxx
    key "eventtask"
    vhost "/"
  </match>

2017-03-02 02:04:47 +0000 [warn]: parameter 'format' in <match syslog>
  @type amqp
  host "random.host.com"
  port 5672
  format json
  user "mozdef"
  pass xxxxxx
  key "eventtask"
  vhost "/"
</match> is not used.

**Comment by sawanoboly** [comment]
@Phrozyn Hi, 

Maybe this Issue is helpful? https://github.com/giraffi/fluent-plugin-amqp/issues/12

**Comment by warmfusion** [comment]
Ok, I see what you're upto here; You're using FluentD + the amqp plugin to capture events from servers to send to brokers, but are then using your own consumer code to read those messages back off the brokers for handling yourselves.

Gotcha. :+1:

Adding an option to specify content-type seems sensible, and while I'm there I'll include an enhancement for #35 and maybe a few other extensions for the other Exchange.publish options (eg TTL, reply_to etc)

**Comment by Phrozyn** [comment]
Awesome! Thanks, this will help immensely!

**Comment by warmfusion** [comment]
This has been fixed by #39 and will be  included in the 0.11.0 release which'll also include #40

**Comment by sawanoboly** [comment]
released as v0.11.0 thanks,
