### ISSUE TITLE
Add CodeClimate token to ci build

### ISSUE THREAD

**Issue by warmfusion** [giraffi/fluent-plugin-amqp#42]
In the `.travis.ci` file there is a ENV property for a codeclimate token.

This needs to be set with the value taken from this page;

https://codeclimate.com/repos/58bdcf969871cf027000007f/coverage_setup

eg

> Your test reporter token is:
>dc87d1856ebee2edd6cde1a500a0400ff6013893beb16e4fa1c831067a695d48

Note: I can't see the above link - and I've guessed what it'll be by exploring the ui, the longer way around is;

1. https://codeclimate.com/github/giraffi/fluent-plugin-amqp
2. Click 'settings'
3. Click 'Test Coverage'
4. Copy link test reporter token
5. Paste into `.travis.yml` on line 11 replacing `<token>`

**Comment by sawanoboly** [comment]
Ah, I couldn't see `settings` too. Because I don't have billing of CodeClimate.
It seems the free plan for Open Source Projects does not support integrations.

**Comment by warmfusion** [comment]
I'm not paying for CodeClimate either, and the token is under "test Coverage' not integrations.

Could you promote me to 'Owner' on this repository instead? I could add the token, and downgrade myself again afterwards.

See https://docs.codeclimate.com/docs/open-source-free#section-administering-open-source-repositories (at the bottom)

**Comment by sawanoboly** [comment]
@warmfusion ok, I've just grant as `admin` of this repo to you.

**Comment by warmfusion** [comment]
Thanks - I'll keep an eye on the CodeClimate UI and update the token when the settings buttons appear

>> Delay: There can sometimes be a short delay (of up to 10 or so minutes) between when you add the repository to Code Climate, and when its Settings link appears. Hang tight, and try again soon!

**Comment by sawanoboly** [comment]
hmm.. I still can't found integration with CodeClimate with open source project...

How about Coveralls Instead?

**Comment by warmfusion** [comment]
CodeClimate includes static code analysis ( https://lima.codeclimate.com/github/giraffi/fluent-plugin-amqp/issues )  which is pretty cool, and CoverAlls needs more access to my organisations that I'm happy with right away (Will investigate further tho)

I'll give the CodeClimate UX an hour or so to update with my changed rights - might drop an email out if nothing changes.

Thanks for the Admin - Once I've got the Code-Climate token in (or an alternative approach) i'll demote myself again.

**Comment by sawanoboly** [comment]
Thank you for investigating. I tried adding coveralls as a trial.

- https://github.com/giraffi/fluent-plugin-amqp/tree/check_coveralls
- https://coveralls.io/github/giraffi/fluent-plugin-amqp
   - Are you granted access to setting on this ?

**Comment by sawanoboly** [comment]
If CodeClimate setting did not work, I feel that it is better to use Coveralls and HoundCI to keep cleanness.

**Comment by warmfusion** [comment]
Nice - Seen your changes on `check_coveralls` and have raised #43 to see how it fits together.

Happy to go with that - my objective was just to get some quality feedback on the plugin arranged.

I've contacted codeclimate to see what they can tell me.

**Comment by sawanoboly** [comment]
Can we close this? And, should I release master as 0.11.0 ?

The current situation is as follows.

- coveralls: report coverage on pull request without threshold of fail.
- houndci: check by rubocop only. It disabled feature that set failed to pull request currently.

**Comment by warmfusion** [comment]
Yup. I got a message back from codeclimate; i need to grant read write access to all my private repos including company ones. So that's not going to happen. 


Please close and release 0.11.0 😁
