### ISSUE TITLE
Not able to connect to Rabbit MQ

### ISSUE THREAD

**Issue by eakarsu** [giraffi/fluent-plugin-amqp#47]
I am trying to test whether or not fluentd/td-agent can send logs to RabbitMQ. I have tested the latest td-agent code + fluent-plugin-amqp v 0..9.3 and the latest fluentd 0.14x. Both are giving me the following error. RabbitMQ version is 3.6x.
Can you please give me some hint on why may cause this issue?

Thanks

W, [2017-04-11T13:57:59.586950 #88298]  WARN -- #<Bunny::Session:0x7f87bea46e40 guest@ism-2.clouddqt.capitalone.com:5672, vhost=/, addresses=[ism-2.clouddqt.capitalone.com:5672]>: An empty frame was received while opening the connection. In RabbitMQ <= 3.1 this could mean an authentication issue.
2017-04-11 13:57:59 -0400 [info]: #0 [amqp_output] Creating new exchange EXCHANGENUM
2017-04-11 13:57:59 -0400 [error]: #0 fluent/engine.rb:222:rescue in run: unexpected error error_class=NoMethodError error="undefined method `next_channel_id' for nil:NilClass"

**Comment by warmfusion** [comment]
``` this could mean an authentication issue.```

Are you able to verify the credentials you are using;

a) Are correct
b) have access to the vhost/exchange/queues involved

I note you're using the Non-TLS port (5672) so i assume you're not trying to use certs for authentication?

Thanks

**Comment by eakarsu** [comment]
I am using certs. Here is more information

What I see is that fluentd is not able to get the latest match line. It perfectly matches all other lines but the last one from log.  I have attached sample input file to test it out.

How can I get the latest match line?

Environment information - Mac OS
Version =  td-agent v2.3.0
Configuration:

<source>
     @type tail
     @id tail_input
     multiline_flush_interval 60s
     format multiline
     format_firstline /(?<date>^\d{4}\/\d{2}\/\d{2})\s+(?<logtime>[^ ]+)\s+\[(?<notice>[^ ]+)\]\s+(?<threadid1>\d+)#(?<threadid2>\d+):\s+\*(?<gwsessionid>\d+)\s+\[lua\]\s+(utils|logger)\.lua:\d+:\s+((dump_(client_request|request_response)\(\))|note[ \(\):]+(\[client_id\:(?<clientid>CLIENTID)\]\s*)?SPLIT LOG(?<splitrange>[ \(\),0-9of]+)):((\s+\[client_id\:(?<clientid2>CLIENTID)\]\s+\[message_id\:(?<messageid>[^ ]+)\](?<responsetext>\s+Response\s+)?(\s+\[upstream_response_time\:\s+(?<upstreamresponsetime>[^ ]+)\s+\]\s+\[body_dump\])?)|(?<splitbody>.*))/
     format1 /(?<date>^\d{4}\/\d{2}\/\d{2})\s+(?<logtime>[^ ]+)\s+\[(?<notice>[^ ]+)\]\s+(?<threadid1>\d+)#(?<threadid2>\d+):\s+\*(?<gwsessionid>\d+)\s+\[lua\]\s+(utils|logger)\.lua:\d+:\s+((dump_(client_request|request_response)\(\))|note[ \(\):]+(\[client_id\:(?<CLIENTID\]\s*)?SPLIT LOG(?<splitrange>[ \(\),0-9of]+)):((\s+\[client_id\:(?<clientid2>CLIENTID)\]\s+\[message_id\:(?<messageid>[^ ]+)\](?<responsetext>\s+Response\s+)?(\s+\[upstream_response_time\:\s+(?<upstreamresponsetime>[^ ]+)\s+\]\s+\[body_dump\])?)|(?<splitbody>.*))/
     format2 /(?<line>((?!\d{4}(\/|-)\d{2}(\/|-)\d{2}).)+)/
     tag debugx.ec2.logt
     path /tmp/error.txt
     pos_file /tmp/java.log.pos
</source>

Example log you can test:

017/04/13 15:59:54 [notice] 9516#9516: *4545087 [lua] utils.lua:550: dump_request_response(): [client_id:CLIENTID] [message_id:MESSAGEID] Response :
POST /app/APPID/confirm HTTP/1.1
HTTP/1.1 200
x-content-type-options : nosniff
expires : 0
content-type : application/json; v=3
connection : keep-alive
content-length : 423
x-version-served : 3
cache-control : no-cache
pragma : no-cache
c1_abc : 
x-xss-protection : 1; mode=block
accept : application/json; v=3
x-frame-options : DENY
{}
2017/04/13 15:59:54 [notice] 9516#9516: *4545087 [lua] utils.lua:548: dump_request_response(): [client_id:CLIENTID] [message_id:MESSAGEID] 
Request :
POST /app/APPID/confirm HTTP/1.1
host: mycompany.com
Accept: application/json; v=3
Api-Key: TRANSITE
Authorization: Bearer masked
Cache-Control: no-cache
Channel-Type: Web
Client-Correlation-Id: 18377860
Content-Type: application/json; v=3
Pragma: no-cache
User-Agent: Jersey/2.6 (HttpUrlConnection 1.8.0_71)
User-Id: web
X-Forwarded-For: x.y.z
X-Forwarded-Port: 443
X-Forwarded-Proto: https
Content-Length: 0
Connection: keep-alive
(body data not available) while sending to client, client: x.y.z, server: 127.0.0.1, request: "POST /app/APPID/confirm HTTP/1.1", upstream: "https://x.y.z:443/app/APPID/confirm", host: "mycompany.com"
t-length : 135
x-version-served : 3
cache-control : no-cache
pragma : no-cache
x-xss-protection : 1; mode=block
accept : application/json; v=3
x-frame-options : DENY
{}

**Comment by eakarsu** [comment]
We have solved this issue. We have to give option :passive = true and :durable = true during getting exchange. We have recognized java and  Bunny library behaves differently when exchange has been already created and the user does not have admin capabilities.

**Comment by warmfusion** [comment]
ah, yeah - that sounds plausable.

I've seen cases where clients connecting try to ensure that the configuration of their target exchange/queues match expectations - setting auto_delete and so on when they're diferent.

Obviously, if the user can't actually change those settings, and/or something else is trying different configuration you'll get strange behaviour.

I'm glad you were able to sort it, and that it makes sense. 👍 Good job.
