### ISSUE TITLE
is fluent-plugin-amqp compatible with td-agent_3.3.0-1

### ISSUE THREAD

**Issue by geib** [giraffi/fluent-plugin-amqp#61]
I am trying to use plugin on new debian host, with td-agent_3.3.0-1. I see the exchange created in the vhost, but never any messages. I added a second "file" type to the td-agent config and then output to a file, that is working fine. I just never see any messages published to rabbitmq.

Thanks,
Mark.

**Comment by warmfusion** [comment]
Hi @geib ,

Can you show me your configuration files for the source and matcher endpoints?

The fact that the exchange is being created suggests that the Matcher is working, have you tried attached a queue manually to the exchange to view incoming events?

The exchange may not show any events on its input if there are no queues bound as rabbitmq will just blackhole events on the exchange if there are no targets.

Cheers

**Comment by geib** [comment]
So I have been able to get things working. It appears that when I included the “tag_key” parameter
I never would see messages published to the exchange, but when I removed it things work. I do
not specify the exchange_type, so the exchange is direct. Now I specify the key, but no tag_key
and all seems good.

I am new to the fluentd domain but learning.

Thanks for the response, and the plugin.

Mark.

**Comment by warmfusion** [comment]
Happy to see you got it working. We've been using this plugin from FluentD 0.12 through to 1.6.2 without any issues, so there's no reason to expect any issues with the TD agent 3.3 which appears to be based on 1.3.3.

Thanks for the feedback.
