### ISSUE TITLE
Dependency versions and 1.9 support

### ISSUE THREAD

**Issue by ulfurinn** [giraffi/fluent-plugin-amqp#9]
I was reading the recent commit log, and got a bit confused. Commit 3cd39d509d20111d4bc0532c8a884009927d40f2 removed support for 1.9, but then f767eda5f69641b4431baa06252b4bf7c4c95358 happened with the apparent purpose of *keeping* support for 1.9. Which of the two is the intent of this library?

I was hoping to bump the bunny dependency to 2.x, but if you intend to support 1.9 and cannot upgrade due to that, I'll have to maintain my own fork.

**Comment by sawanoboly** [comment]
Ah, I was going to give up support ruby1.9, but I just forgot about it.

And, I've never tested this plugin with bunny >2.0. Does it works with bunny2 correctly?

**Comment by ulfurinn** [comment]
Some small fixes are necessary. I'm using bunny 2.2 and fluentd 0.12.

`#queue` and `#exchange` were moved from `Session` to `Channel`, and channels are no longer created automatically, so the code becomes:

```ruby
@bunny.start
@ch = @bunny.create_channel
@queue = @ch.queue(...)
@exch = @ch.exchange(...)
```

Also, heartbeat=0 breaks the protocol, but I can't say if that's a Bunny change or a RabbitMQ change, since I'm running recent versions of both. In any case, it's no longer a safe default.

I can send in a pull request for this.

**Comment by sawanoboly** [comment]
@ulfurinn 

> I can send in a pull request for this.

Oh yes please.
